import 'normalize.css'
import '../scss/index.css'
// own css files here
import { Inter } from 'next/font/google'
import Headr from './components/headr'
import MiddleIner from './components/middleiner'
import Navbar from './components/navbar'
import Footer from './components/footer'
import Service from './components/service'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Headr />
        <MiddleIner />
        <Navbar />
        {children}
        <Service />
        <Footer />
      </body>
    </html>
  )
}
